//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by consultas-Medicas.rc
//
#define DLG_LogIn                       100
#define TXT_LogIn_nameConsult           101
#define TXT_LogIn_Usuario               102
#define TXT_LogIn_password              103
#define TXT_LogIn_SigIn                 104
#define CHK_LogIn_rememberUser          105
#define TXT_LogIn_TypeUser              106
#define COMBO_LogIn_typeUser            107
#define CAP_LOGIN_user                  108
#define CAP_LogIn_Password              109
#define BTN_LogIn_Ingresar              110
#define TXT_LogIn_fecha                 111
#define DLG_PRINCIPAL                   200
#define BTN_PRINC_LogOut                201
#define LIST_PRINCIPAL_citas            202
#define CAP_PRINC_fechaHoy              203
#define TXT_PRINC_fechaHoy              204
#define BTN_PRIN_confirmFecha           205
#define BTN_PRIN_actuCita               206
#define DLG_PACIENTE                    300
#define PAC_CAP_idPaciente              301
#define PAC_CAP_namePaciente            302
#define PAC_CAP_ApePatPaciente          303
#define PAC_CAP_ApeMatPaciente          304
#define PAC_CAP_emailPaciente           305
#define PAC_CAP_telefonoPaciente        306
#define PAC_COMBO_generoPaciente        307
#define PAC_CAP_edadPaciente            308
#define PAC_LIST_ALLpacientes           309
#define PAC_BTN_guardar                 310
#define PAC_BTN_modificar               311
#define PAC_TXT_idPaciente              312
#define PAC_TXT_namePaciente            313
#define PAC_TXT_ApePatPaciente          314
#define PAC_TXT_ApeMatPaciente          315
#define PAC_TXT_emailPaciente           316
#define PAC_TXT_telefonoPaciente        317
#define PAC_TXT_generoPaciente          318
#define PAC_TXT_edadPaciente            319
#define PAC_BTN_borrar                  320
#define PAC_BTN_buscar                  321
#define PAC_BTN_regresar                322
#define DLG_MEDICOS                     400
#define MED_CAP_cedulaMed               401
#define MED_CAP_nombreMed               402
#define MED_CAP_ApePatMed               403
#define MED_CAP_ApeMatMed               404
#define MED_CAP_email                   405
#define MED_CAP_telefono                406
#define MED_COMBO_especialidad          407
#define MED_BTN_borrar                  408
#define MED_BTN_Mod                     409
#define MED_BTN_agregar                 410
#define MED_BTN_masEspeci               411
#define MED_LIST_ALLmed                 413
#define MED_TXT_telefono                414
#define MED_TXT_numCedula               415
#define MED_TXT_nameMedico              416
#define MED_TXT_apePatDoc               417
#define MED_TXT_apeMatDoc               418
#define MED_TXT_emailDoc                419
#define MED_TXT_especialida             420
#define MED_BTN_buscar                  421
#define MED_BTN_regresar                422
#define DLG_CONSULTAS                   500
#define CONS_CAP_folioConsul            501
#define CONS_CAP_nameMed                502
#define CONS_CAP_numPaciente            503
#define CONS_CAP_numDeConsul            504
#define CONS_CAP_nombrePaciente         505
#define CONS_CAL_FECHAConsul            506
#define CONS_COMBO_aConsul              507
#define CONS_COMBO_especi               508
#define CONS_BTN_agendar                509
#define CONS_BTN_reAgendar              510
#define CONS_BTN_diagnostico            511
#define CONS_LIST_consulDispo           512
#define CONS_CAP_horaConsul             513
#define CONS_PseuCAP_ceula              514
#define CONS_TXT_folioConsu             515
#define CONS_TXT_fechaConsulta          516
#define CONS_TXT_horaConsulta           517
#define CONS_TXT_estatusConsulta        518
#define CONS_TXT_numConsultorio         519
#define CONS_COMBO_nombreMED            520
#define CONS_TXT_cedulMedConsulta       521
#define CONS_TXT_nombreMedico           522
#define CONS_TXT_especialidad           523
#define CONS_TXT_numPaciente            524
#define CONS_TXT_nomPac                 525
#define CONS_BTN_regresar               526
#define CONS_CAP_diagCita               527
#define CONS_TXT_diagCita               528
#define CONS_COMBO_CedulaMed            529
#define CONS_COMBO_nombrePaciente       530
#define CONS_COMBO_aConsul2             531
#define DLG_ESPECIALIDAD                600
#define ESP_LIST_Especialidades         601
#define ESP_CAP_clvEspecialidad         602
#define ESP_CAP_especialidad            603
#define ESP_BTN_modEsp                  604
#define ESP_BTN_agregarEsp              605
#define ESP_BTN_elimiEsp                606
#define ESP_TXT_clvEspecialidad         607
#define ESP_TXT_Especialidad            608
#define ESP_BTN_regresarPrincipal       609
#define ESP_BTN_regresarDoctor          610
#define DLG_REPORTES                    700
#define REP_RADIO_PACIENTE              1185
#define REP_RADIO_MED                   1186
#define REP_COMBO_Espec                 1187
#define REP_DATE_FechaIni               1188
#define REP_DATE_fechaFin               1189
#define REP_LIST_consulta               1190
#define REP_LIST_persona                1191
#define REP_TXT_GROUP_escoja            1196
#define REP_TXT_especialidad            1197
#define REP_TXT_FechaFin                1198
#define REP_TXT_FechaIni                1199
#define REP_TXT_pacienteMedico          1200
#define REP_TXT_consultas               1201
#define REP_TXT_reporte                 1202
#define IDR_MENU1                       40002
#define ID_PACIENTES                    40003
#define ID_MEDICOS                      40004
#define ID_CONSULTAS                    40005
#define ID_Especialidad                 40006
#define ID_reporte                      40007
#define ID_algoMas                      40008
#define ID_salir                        40009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        128
#define _APS_NEXT_COMMAND_VALUE         40015
#define _APS_NEXT_CONTROL_VALUE         1204
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
